version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "monitoring-app"
    ports:
      - "8082:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  prometheus:
    image: prom/prometheus:latest
    container_name: "monitoring-prometheus"
    volumes:
      - /opt/prometheus:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app
    links:
      - app
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana:latest
    container_name: "monitoring-grafana"
    volumes:
      - /opt/grafana:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GF_ADMIN_PASSWORD}
    depends_on:
      - prometheus
    links:
      - prometheus
    ports:
      - "3000:3000"
